# used to set env variables in the container.
FROM ubuntu
MAINTAINER Attamapascalpedro@gmail.com

# syntax: "ENV key value"
# where "key" is the key for the env variable,
# and "param1" is the value for the env variable.
ENV var1=Tutorial var2=point
