# used to set the working dir of the container...
FROM ubuntu
MAINTAINER Attamapascalpedro@gmail.com

# syntax: "WORKDIR dirname"
# where "dirname" is the new working dir. If the dir doesnt exist,it will be added.
WORKDIR /newtemp
CMD pwd
