# Used to execute a command at runtime when the container is executed.
FROM ubuntu 
MAINTAINER Attamapascalpedro@gmail.com

# syntax: "CMD command param1"
# where "command" is the command to run when the container is launched,
# and "param1" is the parameter entered to the command. 
CMD ["echo", "hello world"]
