# Used to execute a command at runtime for the container.
FROM ubuntu
MAINTAINER Attamapascalpedro@gmail.com

# syntax: "ENTRYPOINT command param1"
# where "command" is the command to run when the container is launched,
# and "param1" is the parameter entered to the command.
ENTRYPOINT ["echo"]
